apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backup-site
  namespace: backup
  labels:
    app:  backup-site
spec:
  selector:
    matchLabels:
      app: backup-site
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  backup-site
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
  
      containers:
      - name: backup-site
        image: nginx:1.29.4
        resources:
          requests:
            cpu: 128m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi

     

      restartPolicy: Always