apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mysite-hpa
  namespace: web
  labels:
    app: mysite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysite
  minReplicas: 2
  maxReplicas: 16
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

--- 

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mysite-hpa2
  namespace: backup
  labels:
    app: backup-site
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backup-site
  minReplicas: 2
  maxReplicas: 16
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

